# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


def set_default(apps, schema_editor):
    apps.get_model('main', 'UnifiedJob').objects.update(from_awx_ui=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_v350_index_event_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='from_awx_ui',
            field=models.NullBooleanField(default=False, editable=False),
        ),
        migrations.RunPython(set_default)
    ]
